## Review template file for QE-Core job groups in OSD
# See: https://confluence.suse.com/display/qasle/Bugbusters+and+Review+Shifts#BugbustersandReviewShifts-Links

Instance = "https://openqa.suse.de"              # openQA instance to query
RabbitMQ = "amqps://suse:suse@rabbit.suse.de"    # RabbitMQ instance to query
RabbitMQTopic = "suse.openqa.job.done"           # RabbitMQ topic to query
HideStatus = ["scheduled", "passed", "softfailed", "cancelled", "skipped", "running", "uploading", "parallel_failed", "reviewed", "user_cancelled"]  # Hide jobs in defined states
RefreshInterval = 60                             # Refresh from API once every minute
MaxJobs = 20                                     # Max. job per group to display
GroupBy = "groups"                               # Group by defined groups ("none" or "groups")
RequestJobLimit = 100                            # Query up to 100 jobs per http request

# SLE Maintenance: Test Repo / Core Maintenance Updates

[[Groups]]
Name = "SLE Maintenance: Test Repo / Core Maintenance Updates"
Params = { groupid = "414", build = "" }
MaxLifetime = 86400

# Maintenance Single Incidents

[[Groups]]
Name = "Maintenance: SLE 15-SP4 Incidents"
Params = { groupid = "439", build = "" }
MaxLifetime = 86400

[[Groups]]
Name = "Maintenance: SLE 15-SP3 Incidents"
Params = { groupid = "367", build = "" }
MaxLifetime = 86400

[[Groups]]
Name = "Maintenance: SLE 15-SP2 Incidents"
Params = { groupid = "306", build = "" }
MaxLifetime = 86400

[[Groups]]
Name = "Maintenance: SLE 15-SP1 Incidents"
Params = { groupid = "233", build = "" }
MaxLifetime = 86400

[[Groups]]
Name = "Maintenance: SLE 15 GA Incidents"
Params = { groupid = "159", build = "" }
MaxLifetime = 86400

[[Groups]]
Name = "Maintenance: SLE 12-SP5 Incidents"
Params = { groupid = "282", build = "" }
MaxLifetime = 86400

[[Groups]]
Name = "Maintenance: SLE 12-SP4 Incidents"
Params = { groupid = "215", build = "" }
MaxLifetime = 86400

[[Groups]]
Name = "Maintenance: SLE 12-SP3 Incidents"
Params = { groupid = "106", build = "" }
MaxLifetime = 86400

[[Groups]]
Name = "Maintenance: SLE 12-SP2 Incidents"
Params = { groupid = "53", build = "" }
MaxLifetime = 86400

# Quarterly Refresh

[[Groups]]
Name = "Maintenance: QR SLE 15-SP4"
Params = { groupid = "458", build = "" }
MaxLifetime = 86400

[[Groups]]
Name = "Maintenance: QR SLE 15-SP3"
Params = { groupid = "373", build = "" }
MaxLifetime = 86400

# Functional

[[Groups]]
Name = "SLE 15 - Functional"
Params = { groupid = "110", build = "" }
MaxLifetime = 86400

