## Review configuration for QE-C related jobs on OSD

Instance = "https://openqa.suse.de"              # openQA instance to query
RabbitMQ = "amqps://suse:suse@rabbit.suse.de"    # RabbitMQ instance to query
RabbitMQTopic = "suse.openqa.job.done"           # RabbitMQ topic to query
HideStatus = ["scheduled", "passed", "softfailed", "cancelled", "skipped", "running", "uploading", "parallel_failed", "reviewed", "user_cancelled"]  # Hide jobs in defined states
RefreshInterval = 60                             # Refresh from API once every minute
MaxJobs = 20                                     # Max. job per group to display
GroupBy = "groups"                               # Group by defined groups ("none" or "groups")

## BCI and Base images #########################################################

[[Groups]]
Name = "BCI Base Images 15-SP6"
Params = { groupid = "538", build = "" }
MaxLifetime = 86400

[[Groups]]
Name = "BCI Base Images 15-SP5"
Params = { groupid = "475", build = "" }
MaxLifetime = 86400

[[Groups]]
Name = "BCI Base Images 15-SP4"
Params = { groupid = "443", build = "" }
MaxLifetime = 86400

[[Groups]]
Name = "BCI Base Images 15-SP3"
Params = { groupid = "442", build = "" }
MaxLifetime = 86400

[[Groups]]
Name = "BCI Language Images"
Params = { groupid = "444", build = "" }
MaxLifetime = 86400

[[Groups]]
Name = "BCI Application Images"
Params = { groupid = "445", build = "" }
MaxLifetime = 86400

[[Groups]]
Name = "Base Images (pre-BCI, <15SP3)"
Params = { groupid = "453", build = "" }
MaxLifetime = 86400

[[Groups]]
Name = "SUMA images"
Params = { groupid = "516", build = "" }
MaxLifetime = 86400

[[Groups]]
Name = "BCI repo"
Params = { groupid = "428", build = "" }
MaxLifetime = 86400


## Container Maintenance updates ###############################################

[[Groups]]
Name = "Containers Maintenance Updates 15-SP6"
Params = { groupid = "417", build = "%yesterday%-1", version="15-SP6" }
MaxLifetime = 86400

[[Groups]]
Name = "Containers Maintenance Updates 15-SP5"
Params = { groupid = "417", build = "%yesterday%-1", version="15-SP5" }
MaxLifetime = 86400

[[Groups]]
Name = "Containers Maintenance Updates 15-SP4"
Params = { groupid = "417", build = "%yesterday%-1", version="15-SP4" }
MaxLifetime = 86400

[[Groups]]
Name = "Containers Maintenance Updates 15-SP3"
Params = { groupid = "417", build = "%yesterday%-1", version="15-SP3" }
MaxLifetime = 86400

[[Groups]]
Name = "Containers Maintenance Updates 15-SP2"
Params = { groupid = "417", build = "%yesterday%-1", version="15-SP2" }
MaxLifetime = 86400

[[Groups]]
Name = "Containers Maintenance Updates 15-SP1"
Params = { groupid = "417", build = "%yesterday%-1", version="15-SP1" }
MaxLifetime = 86400

[[Groups]]
Name = "Containers Maintenance Updates 15"
Params = { groupid = "417", build = "%yesterday%-1", version="15" }
MaxLifetime = 86400

[[Groups]]
Name = "Containers Maintenance Updates 12-SP5"
Params = { groupid = "417", build = "%yesterday%-1", version="12-SP5" }
MaxLifetime = 86400

# Create host disk images

[[Groups]]
Name = "Create bootable host HDDs"
Params = { groupid = "377", build = "" }
MaxLifetime = 86400


## JeOS/MinimalVM Maintenance updates ##########################################

[[Groups]]
Name = "JeOS Maintenance Updates 15-SP6"
Params = { groupid = "419", build = "%yesterday%-1", version = "15-SP6" }
MaxLifetime = 86400

[[Groups]]
Name = "JeOS Maintenance Updates 15-SP5"
Params = { groupid = "419", build = "%yesterday%-1", version = "15-SP5" }
MaxLifetime = 86400

[[Groups]]
Name = "JeOS Maintenance Updates 15-SP4"
Params = { groupid = "419", build = "%yesterday%-1", version = "15-SP4" }
MaxLifetime = 86400

[[Groups]]
Name = "JeOS Maintenance Updates 15-SP3"
Params = { groupid = "419", build = "%yesterday%-1", version = "15-SP3" }
MaxLifetime = 86400

[[Groups]]
Name = "JeOS Maintenance Updates 15-SP2"
Params = { groupid = "419", build = "%yesterday%-1", version = "15-SP2" }
MaxLifetime = 86400

[[Groups]]
Name = "JeOS Maintenance Updates 15-SP1"
Params = { groupid = "419", build = "%yesterday%-1", version = "15-SP1" }
MaxLifetime = 86400

[[Groups]]
Name = "JeOS Maintenance Updates 12-SP5"
Params = { groupid = "419", build = "%yesterday%-1", version = "12-SP5" }
MaxLifetime = 86400


## PublicCloud Maintenance updates #############################################

[[Groups]]
Name = "PublicCloud Maintenance Updates 15-SP6"
Params = { groupid = "427", build = "%yesterday%-1", version="15-SP6" }
[[Groups]]
Name = "PublicCloud Maintenance Updates 15-SP5"
Params = { groupid = "427", build = "%yesterday%-1", version="15-SP5" }
[[Groups]]
Name = "PublicCloud Maintenance Updates 15-SP4"
Params = { groupid = "427", build = "%yesterday%-1", version="15-SP4" }
[[Groups]]
Name = "PublicCloud Maintenance Updates 15-SP3"
Params = { groupid = "427", build = "%yesterday%-1", version="15-SP3" }
[[Groups]]
Name = "PublicCloud Maintenance Updates 15-SP2"
Params = { groupid = "427", build = "%yesterday%-1", version="15-SP2" }
[[Groups]]
Name = "PublicCloud Maintenance Updates 15-SP1"
Params = { groupid = "427", build = "%yesterday%-1", version="15-SP1" }
[[Groups]]
Name = "PublicCloud Maintenance Updates 12-SP5"
Params = { groupid = "427", build = "%yesterday%-1", version="12-SP5" }

[[Groups]]
Name = "Public Cloud Single Incidents"
Params = { groupid = "430" }
MaxLifetime = 86400

# Create openQA helper instance disk image

[[Groups]]
Name = "Create publiccloud-tools HDD"
Params = { groupid = "276", build = "" }
MaxLifetime = 86400

## SLE Micro image updates

[[Groups]]
Name = "SLE Micro Toolbox updates"
Params = { groupid = "451" }
MaxLifetime = 86400

[[Groups]]
Name = "SLE Micro for Rancher"
Params = { groupid = "449" }
MaxLifetime = 86400


## SLE Micro Maintenance updates ###############################################

[[Groups]]
Name = "SL Micro 6.0 Staging Updates for Containers"
Params = { groupid = "566" }
MaxLifetime = 86400

[[Groups]]
Name = "SL Micro 6.0 Product Updates for Containers"
Params = { groupid = "572" }
MaxLifetime = 86400

[[Groups]]
Name = "SLE Micro Maintenance Updates 5.5"
Params = { groupid = "420", build = "%yesterday%-1", version = "5.5" }
MaxLifetime = 86400

[[Groups]]
Name = "SLE Micro Maintenance Updates 5.4"
Params = { groupid = "420", build = "%yesterday%-1", version = "5.4" }
MaxLifetime = 86400

[[Groups]]
Name = "SLE Micro Maintenance Updates 5.3"
Params = { groupid = "420", build = "%yesterday%-1", version = "5.3" }
MaxLifetime = 86400

[[Groups]]
Name = "SLE Micro Maintenance Updates 5.2"
Params = { groupid = "420", build = "%yesterday%-1", version = "5.2" }
MaxLifetime = 86400

[[Groups]]
Name = "SLE Micro Maintenance Updates 5.1"
Params = { groupid = "420", build = "%yesterday%-1", version = "5.1" }
MaxLifetime = 86400

## Single Incidents

[[Groups]]
Name = "SLE Micro Maintenance Incidents for 5.5"
Params = { groupid = "528" }
MaxLifetime = 86400

[[Groups]]
Name = "SLE Micro Maintenance Incidents for 5.4"
Params = { groupid = "486" }
MaxLifetime = 86400

[[Groups]]
Name = "SLE Micro Maintenance Incidents for 5.3"
Params = { groupid = "484" }
MaxLifetime = 86400

[[Groups]]
Name = "SLE Micro Maintenance Incidents for 5.2"
Params = { groupid = "483" }
MaxLifetime = 86400

[[Groups]]
Name = "SLE Micro Maintenance Incidents for 5.1"
Params = { groupid = "482" }
MaxLifetime = 86400


## WSL builds ##################################################################

[[Groups]]
Name = "SLE 15-SP6 WSL"
Params = { groupid = "595" }
MaxLifetime = 86400

[[Groups]]
Name = "SLE 15-SP5 WSL"
Params = { groupid = "461" }
MaxLifetime = 86400

## Windows KVM Installation

[[Groups]]
Name = "Windows 11 installation"
Params = { version="11", groupid="287" }
MaxLifetime = 86400

[[Groups]]
Name = "Windows 10 installation"
Params = { version="10", groupid="287" }
MaxLifetime = 86400
