## Review template file for container test runs on OSD

Instance = "https://openqa.suse.de"              # openQA instance to query
RabbitMQ = "amqps://suse:suse@rabbit.suse.de"    # RabbitMQ instance to query
RabbitMQTopic = "suse.openqa.job.done"           # RabbitMQ topic to query
HideStatus = ["scheduled", "passed", "softfailed", "cancelled", "skipped", "running", "uploading", "parallel_failed", "reviewed", "user_cancelled"]  # Hide jobs in defined states
RefreshInterval = 60                             # Refresh from API once every minute
MaxJobs = 20                                     # Max. job per group to display
GroupBy = "groups"                               # Group by defined groups ("none" or "groups")
RequestJobLimit = 100                            # Query up to 100 jobs per http request

## BCI and Base images
[[Groups]]
Name = "BCI Base Images 16"
Params = { groupid = "608", build = "" }
MaxLifetime = 86400

[[Groups]]
Name = "BCI Base Images 15-SP6"
Params = { groupid = "538", build = "" }
MaxLifetime = 86400

[[Groups]]
Name = "BCI Base Images 15-SP5"
Params = { groupid = "475", build = "" }
MaxLifetime = 86400

[[Groups]]
Name = "BCI Base Images 15-SP4"
Params = { groupid = "443", build = "" }
MaxLifetime = 86400

[[Groups]]
Name = "BCI Base Images 15-SP3"
Params = { groupid = "442", build = "" }
MaxLifetime = 86400

[[Groups]]
Name = "BCI Language Images"
Params = { groupid = "444", build = "" }
MaxLifetime = 86400

[[Groups]]
Name = "BCI Application Images"
Params = { groupid = "445", build = "" }
MaxLifetime = 86400

[[Groups]]
Name = "Base Images (pre-BCI, <15SP3)"
Params = { groupid = "453", build = "" }
MaxLifetime = 86400

[[Groups]]
Name = "SUMA images"
Params = { groupid = "516", build = "" }
MaxLifetime = 86400

[[Groups]]
Name = "BCI repo"
Params = { groupid = "428", build = "" }
MaxLifetime = 86400
