## Review template file for SLE micro test runs on OSD

Instance = "https://openqa.suse.de"              # openQA instance to query
RabbitMQ = "amqps://suse:suse@rabbit.suse.de"    # RabbitMQ instance to query
RabbitMQTopic = "suse.openqa.job.done"           # RabbitMQ topic to query
HideStatus = [ "scheduled", "passed", "softfailed", "running", "reviewed", "user_cancelled"]  # Hide jobs in defined states
RefreshInterval = 60                             # Refresh from API once every minute
MaxJobs = 20                                     # Max. job per group to display
GroupBy = "groups"                               # Group by defined groups ("none" or "groups")
RequestJobLimit = 100                            # Query up to 100 jobs per http request

## SLE Micro image updates

[[Groups]]
Name = "SLE Micro Toolbox updates"
Params = { groupid = "451" }
MaxLifetime = 86400

[[Groups]]
Name = "SLE Micro for Rancher"
Params = { groupid = "449" }
MaxLifetime = 86400

## Maintenance updates

[[Groups]]
Name = "SLE Micro Container Maintenance Updates 5.5"
Params = { groupid = "420", build = "%yesterday%-1", version = "5.5" }
MaxLifetime = 86400

[[Groups]]
Name = "SLE Micro Container Maintenance Updates 5.4"
Params = { groupid = "420", build = "%yesterday%-1", version = "5.4" }
MaxLifetime = 86400

[[Groups]]
Name = "SLE Micro Container Maintenance Updates 5.3"
Params = { groupid = "420", build = "%yesterday%-1", version = "5.3" }
MaxLifetime = 86400

[[Groups]]
Name = "SLE Micro Container Maintenance Updates 5.2"
Params = { groupid = "420", build = "%yesterday%-1", version = "5.2" }
MaxLifetime = 86400

[[Groups]]
Name = "SLE Micro Container Maintenance Updates 5.1"
Params = { groupid = "420", build = "%yesterday%-1", version = "5.1" }
MaxLifetime = 86400

## Single Incidents

[[Groups]]
Name = "SLE Micro Maintenance Incidents for 5.5"
Params = { groupid = "528" }
MaxLifetime = 86400

[[Groups]]
Name = "SLE Micro Maintenance Incidents for 5.4"
Params = { groupid = "486" }
MaxLifetime = 86400

[[Groups]]
Name = "SLE Micro Maintenance Incidents for 5.3"
Params = { groupid = "484" }
MaxLifetime = 86400

[[Groups]]
Name = "SLE Micro Maintenance Incidents for 5.2"
Params = { groupid = "483" }
MaxLifetime = 86400

[[Groups]]
Name = "SLE Micro Maintenance Incidents for 5.1"
Params = { groupid = "482" }
MaxLifetime = 86400

## SL Micro 6.0+
[[Groups]]
Name = "SL Micro 6.0 Staging Updates - Containers"
Params = { groupid = "566" }
MaxLifetime = 86400

[[Groups]]
Name = "SL Micro 6.0 Product Increments - Containers"
Params = { groupid = "572" }
MaxLifetime = 86400
