## Review template file for PublicCloud test runs on OSD

Instance = "https://openqa.suse.de"              # openQA instance to query
RabbitMQ = "amqps://suse:suse@rabbit.suse.de"    # RabbitMQ instance to query
RabbitMQTopic = "suse.openqa.job.done"           # RabbitMQ topic to query
HideStatus = ["scheduled", "passed", "softfailed", "cancelled", "skipped", "running", "uploading", "parallel_failed", "reviewed", "user_cancelled"]  # Hide jobs in defined states
Notify = false                                   # No notifications by default
RefreshInterval = 60                             # Refresh from API once every minute
MaxJobs = 20                                     # Max. job per group to display
GroupBy = "groups"                               # Group by defined groups ("none" or "groups")
DefaultParams = { distri = "sle" }               # Set of default parameters
RequestJobLimit = 100                            # Query up to 100 jobs per http request

## Maintenance updates
[[Groups]]
Name = "PublicCloud Maintenance Updates 15-SP6"
Params = { groupid = "427", build = "%yesterday%-1", version="15-SP6" }
[[Groups]]
Name = "PublicCloud Maintenance Updates 15-SP5"
Params = { groupid = "427", build = "%yesterday%-1", version="15-SP5" }
[[Groups]]
Name = "PublicCloud Maintenance Updates 15-SP4"
Params = { groupid = "427", build = "%yesterday%-1", version="15-SP4" }
[[Groups]]
Name = "PublicCloud Maintenance Updates 15-SP3"
Params = { groupid = "427", build = "%yesterday%-1", version="15-SP3" }
[[Groups]]
Name = "PublicCloud Maintenance Updates 15-SP2"
Params = { groupid = "427", build = "%yesterday%-1", version="15-SP2" }
[[Groups]]
Name = "PublicCloud Maintenance Updates 15-SP1"
Params = { groupid = "427", build = "%yesterday%-1", version="15-SP1" }
[[Groups]]
Name = "PublicCloud Maintenance Updates 12-SP5"
Params = { groupid = "427", build = "%yesterday%-1", version="12-SP5" }

# SLE-Micro
[[Groups]]
Name = "PublicCloud Maintenance Updates 5.5"
Params = { groupid = "532", build = "%yesterday%-1", version="5.5" }
[[Groups]]
Name = "PublicCloud Maintenance Updates 5.4"
Params = { groupid = "532", build = "%yesterday%-1", version="5.4" }
[[Groups]]
Name = "PublicCloud Maintenance Updates 5.3"
Params = { groupid = "532", build = "%yesterday%-1", version="5.3" }
[[Groups]]
Name = "SLEM Product Increments"
Params = { groupid = "613" }
MaxLifetime = 86400


[[Groups]]
Name = "Public Cloud Single Incidents"
Params = { groupid = "430" }
MaxLifetime = 86400

# Create openQA helper instance disk image

[[Groups]]
Name = "Create publiccloud-tools HDD"
Params = { groupid = "276", build = "" }
MaxLifetime = 86400

